# Generated by Django 6.0.7 on 2026-08-05 22:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_create_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use uppercase letters, numbers, hyphens, and underscores only.', regex='^[A-Z0-9_-]+$')])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use uppercase letters, numbers, hyphens, and underscores only.', regex='^[A-Z0-9_-]+$')])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_areas', to='core.site')),
            ],
            options={
                'ordering': ['site__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use uppercase letters, numbers, hyphens, and underscores only.', regex='^[A-Z0-9_-]+$')])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('production_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lines', to='core.productionarea')),
            ],
            options={
                'ordering': ['production_area__site__code', 'production_area__code', 'code'],
                'constraints': [models.UniqueConstraint(fields=('production_area', 'code'), name='unique_line_code_per_area')],
            },
        ),
        migrations.AddConstraint(
            model_name='productionarea',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_area_code_per_site'),
        ),
    ]
