# Generated by Django 6.0.7 on 2026-08-07 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_operational_reference_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Use uppercase letters, numbers, hyphens, and underscores only.', regex='^[A-Z0-9_-]+$')])),
                ('planned_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.product')),
            ],
            options={
                'ordering': ['-created_at', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('good_quantity', models.PositiveIntegerField(default=0)),
                ('rejected_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.productionline')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.shift')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gt', 0)), name='work_order_planned_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('good_quantity__gte', 0)), name='production_run_good_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_quantity__gte', 0)), name='production_run_rejected_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='production_run_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('work_order',), name='unique_active_run_per_work_order'),
        ),
    ]
