# Generated by Django 6.0.7 on 2026-08-07 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_work_orders_production_runs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rejected_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='production_run_good_quantity_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='production_run_rejected_quantity_nonnegative',
        ),
        migrations.AddField(
            model_name='productionentry',
            name='production_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='core.productionrun'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='good_quantity',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='rejected_quantity',
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.CheckConstraint(condition=models.Q(('good_quantity__gte', 0)), name='production_entry_good_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_quantity__gte', 0)), name='production_entry_rejected_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.CheckConstraint(condition=models.Q(('good_quantity__gt', 0), ('rejected_quantity__gt', 0), _connector='OR'), name='production_entry_quantity_required'),
        ),
    ]
