# Generated by Django 6.0.7 on 2026-08-08 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_production_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_downtime_events', to=settings.AUTH_USER_MODEL)),
                ('downtime_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='core.downtimereason')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_downtime_events', to=settings.AUTH_USER_MODEL)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='core.productionrun')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='downtime_event_end_not_before_start'), models.CheckConstraint(condition=models.Q(models.Q(('closed_by__isnull', True), ('ended_at__isnull', True)), models.Q(('closed_by__isnull', False), ('ended_at__isnull', False)), _connector='OR'), name='downtime_event_close_state_consistent'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('production_run',), name='unique_open_downtime_per_production_run')],
            },
        ),
    ]
